### ISSUE TITLE
Viewer basic structure

### ISSUE THREAD

**Issue by flavens** [dasch-swiss/knora-ui-ng-lib#1]
- viewer.module
    - property 
        - operation components (crud)
          > one component per operation, dealing with the different value types defined in type-information components 
        - type-information components (knora value types)
          > one component per value type (e.g. KnoraDate, KnoraInt... independent of the CRUD operations) that can be used in operation components 
    - views
        - resource view
        - property view
        - lists
       - search-results
    - representation (media type)

**Comment by flavens** [comment]
How can we switch between the different operation components (e.g. display a value (read), then edit this value (update), and finally reload and display the updated value)

**Comment by flavens** [comment]
**Project examples with one element component implementing all CRUD-operation methods in the TS file**
https://codeburst.io/crud-with-angular-5d8f39805c49
https://adrianmejia.com/angular-2-tutorial-create-a-crud-app-with-angular-cli-and-typescript/

**Project example with CRUD-operation components**
https://www.javaguides.net/2019/06/angular-8-crud-example-tutorial.html

**Comment by tobiasschweizer** [comment]
# Knora-ui lib

## General
The knora-ui elements will be organized in **one** Angular lib that can then be published on npm. The lib's internal structure (its directory structure) can be similar to the structure of the previous npm libs (core, viewer etc.). Also it can consist of different modules.

## Viewer

### Structure
The viewer has a part called `values` and a part called `operations`. `values` contains specific components for the Knora value types such as integer, date etc. These components share a common interface. However, each component can have additional specific inputs and outputs for further configuration. `operations` handles the tasks that are common to all values types and decides which component to use to handle the value specific tasks.

For the new viewer I did some prototyping which you can find here: https://github.com/tobiasschweizer/angular-lib.

### API

#### Values

All value specific components are derived from a common base class so that they share a minimal public API:

```ts
export abstract class BaseValueComponent {

    @Input() abstract displayValue?: ReadValue;

    @Input() mode: 'read' | 'update' | 'create' | 'search';

    ...

    abstract resetValue(): void;

    abstract getNewValue(): CreateValue;

    abstract getUpdatedValue(): UpdateValue;
}
```

Each value component will have an optional input `displayValue` that will have to be implement for its specific type. It allows to set an initial value which is needed for display (read-mode) and edit a value (update-mode). 

Each value component has to be initialized to a specific `mode`: read, update, create, search via an input. The mode can be changed, so a displayed value can be edited.

When a value is being created or updated, the new value can be obtained via `getNewValue()` or `getUpdatedValue()` respectively.

`resetValue` value sets a value back to its initial state (for instance when an update operation is aborted).

**Comment by tobiasschweizer** [comment]
some experiments with [mermaid](https://mermaid-js.github.io/mermaid-live-editor/):

```
classDiagram
    class BaseComponent
    BaseComponent : +@Input displayValue: ReadValue
    BaseComponent : +@Input mode: 'read' | 'update' | 'create' | 'search'
    BaseComponent : +resetValue(): void
    BaseComponent : +getNewValue(): CreateValue
    BaseComponent : +getUpdatedValue(): UpdateValue

    class DateValueComponent
    DateValueComponent <|-- BaseComponent

    class IntegerValueComponent
    IntegerValueComponent <|-- BaseComponent
```

**Comment by tobiasschweizer** [comment]
```mermaid
graph TB

  SubGraph1 --> SubGraph1Flow
  subgraph "SubGraph 1 Flow"
  SubGraph1Flow(SubNode 1)
  SubGraph1Flow -- Choice1 --> DoChoice1
  SubGraph1Flow -- Choice2 --> DoChoice2
  end

  subgraph "Main Graph"
  Node1[Node 1] --> Node2[Node 2]
  Node2 --> SubGraph1[Jump to SubGraph1]
  SubGraph1 --> FinalThing[Final Thing]
end
```

**Comment by tobiasschweizer** [comment]
```mermaid
classDiagram
    
    class DisplayValuesComponent {
      +@Input ReadValue[] displayValues
      +@Input ViewerConfiguration
      
      +@ViewChildren QueryList<BaseValueComponent> valueComponents
    }
```

**Comment by tobiasschweizer** [comment]
## Analyzing Permissions

**Comment by flavens** [comment]
The GUI attributes from the Salsah GUI ontology are not up-to-date and some attributes are missing. We can either extend the actual Salsah GUI ontology with GUI new elements or create a new ontology.

**Comment by flavens** [comment]
List of GUI/Form elements needed: [dasch-swiss/knora-ui/issues/358](https://github.com/dasch-swiss/knora-ui/issues/358). Links to Angular Material Components included.

**Comment by lrosenth** [comment]
Please take into account that the comment is part of the value component!

**Comment by tobiasschweizer** [comment]
# Validation

I have realized that validation depends on the mode:
- "read": no validators needed
- "update": a value is required, it has to be of the correct type (e.g., numeric), and it has to be different from the previous value
- "create": a value is required, it has to be of the correct type (e.g., numeric)

I think when switching the mode and/or resting the display value, the validators have to be set accordingly.

**Comment by flavens** [comment]
@tobiasschweizer a large part of your doc here should be copied in knora-proposals in a new design file to describe this new major feature (requested by Ivan)

**Comment by tobiasschweizer** [comment]
@flavens Ok, I will do that, thanks!

**Comment by tobiasschweizer** [comment]
@flavens Please have a look at https://github.com/dasch-swiss/knora-proposals/blob/master/designs/2020-02-10-knora-ui-viewer.md

**Comment by flavens** [comment]
> @flavens Please have a look at https://github.com/dasch-swiss/knora-proposals/blob/master/designs/2020-02-10-knora-ui-viewer.md

Good text, but I would add some precisions:
- "An Angular module called "knora-ui viewer" should be created." -> you should mention everywhere that we are creating a new knora-ui repo that will **refactor** (and not create) the modules.
- you never mention the "delete" feature that will also be implemented
- this part in the proposal: "Before, @knora/viewer and @knora/search **defined components** that now can be combined into one per Knora value, reducing redundancy and facilitating maintenance." -> you could precise that it is only the value elements to build the views/search form and not the combination of the 2 modules in 1 (because for me this sentence is a bit confusing)
- you also could mention briefly how we will handle values permissions

**Comment by flavens** [comment]
@tobiasschweizer I also would like to talk about the design of the GUI elements **before** we start to develop all the components. I am still working on the general views but this is what I have today to start the discussion.

- André did a mockup on each element in read/edit mode:
![properties-and-elements](https://user-images.githubusercontent.com/29532462/74143506-3538a280-4bfb-11ea-8e5a-afdfde03e477.png)

- General views for each mode, except "search":
![view_combination](https://user-images.githubusercontent.com/29532462/74143693-8d6fa480-4bfb-11ea-9dbb-6daae72bd42e.png)

**Comment by tobiasschweizer** [comment]
@flavens Thanks for your comments! 

Should there be an additional input for the GUI element (e.g., input or textarea)?

**Comment by flavens** [comment]
> Should there be an additional input for the GUI element (e.g., HTML input or textarea for text)?
Yes, we should try with an input. It won't be the case for each value and comment will always be a textarea.

**Comment by tobiasschweizer** [comment]
> Yes, we should try with an input. It won't be the case for each value and comment will always be a textarea.

I think each value component can have custom configuration inputs (see https://github.com/dasch-swiss/knora-ui-ng-lib/issues/1#issuecomment-574588516) in addition to those defined on the base class.

**Comment by flavens** [comment]
@tobiasschweizer @mdelez some suggestions:
- we must use the prefix "kui" for each component (e.g. kui-text-value-as-string)
- create and delete operations are missing (but should be already in your todo list)
- implement the possibility to display a hint message or an error message after each value field (mat-hint and mat-error -> see [Input material component](https://v8.material.angular.io/components/input/examples))
