### ISSUE TITLE
Viewer Value Component: ColorValueComponent

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/knora-ui-ng-lib#10]
Implement `BaseValueComponent` for a `ColorValue`.

**Comment by flavens** [comment]
GUI element: we should try to implement the [ngx-color-picker](https://www.npmjs.com/package/ngx-color-picker)
alternative option: [Material Input](https://material.angular.io/components/input/overview)

**Comment by tobiasschweizer** [comment]
helpful resources:
- https://indepth.dev/never-again-be-confused-when-implementing-controlvalueaccessor-in-angular-forms/
- https://material.angular.io/guide/creating-a-custom-form-field-control

You  can also look at #26
