### ISSUE TITLE
Viewer Value Component: GeonameValueComponent

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/knora-ui-ng-lib#12]
Implement `BaseValueComponent` for a `GeonameValue`.

**Comment by flavens** [comment]
GUI element:
> if we need a map, we should try the official package [@angular/google-maps](https://www.npmjs.com/package/@angular/google-maps) BUT this component is part of Angular 9 release
> if the value is just a string: [Material Input](https://v8.material.angular.io/components/input/overview)
