### ISSUE TITLE
Viewer Value Component: IntervalValueComponent

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/knora-ui-ng-lib#13]
Implement `BaseValueComponent` for an `IntervalValue`.

Consider making a custom Angular Material  form field control since an interval needs two input fields but there is only one form control for the actual value: https://material.angular.io/guide/creating-a-custom-form-field-control

The actual value would be an object with a start and an end member.

**Comment by flavens** [comment]
GUI element: a combination of [Material Input](https://material.angular.io/components/input/overview)
