### ISSUE TITLE
Viewer Value Component: LinkValueComponent 

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/knora-ui-ng-lib#14]
Implement `BaseValueComponent` for a `LinkValue`.

**Comment by flavens** [comment]
GUI element: [Material autocomplete](https://material.angular.io/components/autocomplete/overview)

**Comment by tobiasschweizer** [comment]
I think some of this logic can be reused to get the resources from Knora: https://github.com/dasch-swiss/knora-ui/blob/master/projects/knora/search/src/lib/extended-search/select-property/specify-property-value/link-value/link-value.component.ts
