### ISSUE TITLE
Describe Structure of CRUD components

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/knora-ui-ng-lib#46]
# Shared Logic for Angular CRUD UI components

### General

We want to create an Angular module of CRUD UI components for different value types backed by our CMS [Knora](https://www.knora.org). All value types have their specifics (e.g., integer, plain text, date), but a value is also a general concept that can be considered type independent. For example, each value can have a comment.

### CRUD Operations

For each value type, the following operations should be supported:

- read (display an existing value and its comment)
- update / edit (make a new version of an existing value and/or its comment)
- create (create a new value with or without a comment)
- delete (delete an existing value)
- search (search for an existing value, to be done in the future)

### Validation

Each value should be validated before an update or a new value can be submitted:

- the user input has to meet the restrictions defined for the type (e.g, an integer cannot have fractions)
- when updating / editing a value, the new version has to be different from the existing version (no redundant versions are allowed). Changing the comment on a value is sufficient.

### State Management

The UI components should allow the user to perform different operations on a value. After each operation, the UI component should be in a defined state. For example, when the user aborts the update of a value, the existing value should be correctly reinitialised, restoring the original state. Another example could be that the user creates a new value, and this new value gets read back from the CMS, allowing for further update operations.

**Comment by tobiasschweizer** [comment]
## Solution

We decided to create an Angular component per value type and to make each of these components a subclass of an abstract base class. We refer to these components as **value components**, for instance `IntValueComponent` for an integer value. A value component knows how to display a value of a given type and how to update it or create a new value interacting with a user.

Based on the public API shared by all value components we are able to create components that actually communicate with the backend: read, update, create, and delete values. We refer to these as **operation** components. Since all value types share some commonalities, there is no need to develop value specific components for CRUD operations.

**Comment by tobiasschweizer** [comment]
### Complex Values

The concept outlined above works fine for primitive values like a number. A primitive value can be simple set to the the `FormControl`, displayed and manipulated the template, and read back from the `FormControl`. However, some value types are more complex than that. For example, our backend has an interval type that consists of two decimals. In our template, we would like the user to enter two decimal numbers in two different input fields. Since the base class just defines one `FormControl` for a value, we make a custom form form field control and handle the complexity there. To the parent, it still looks like one value.

**Comment by tobiasschweizer** [comment]
### CRUD / Operations Components

So far, we have added a [`DisplayEditComponent`](https://github.com/dasch-swiss/knora-ui-ng-lib/blob/master/projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts) that displays any value and makes it editable, the necessary permissions provided.

The `DisplayEditComponent` chooses the appropriate component in is temple to display a given value. It holds a reference to this component via the `@ViewChild` decorator:

https://github.com/dasch-swiss/knora-ui-ng-lib/blob/dc9c557aaa6e86da0d8c687d031d0b8457e460c1/projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts#L24

Note that the type is `BaseValueComponent` which **all** value components are derived from.

**Comment by tobiasschweizer** [comment]
## Summary

**Comment by tobiasschweizer** [comment]
## Summary

**Comment by tobiasschweizer** [comment]
## Acknowledgements

**Comment by tobiasschweizer** [comment]
## Possible Improvements

- consider using generics: the component's type has to be consistent with the type of value set in the `FormControl` and returned by `getInitValue`
- consider making `standardValidatorFunc` call a method for value comparison (equivalence check), so only this method would have to overridden (logic for comments is always the same).

**Comment by maxkoretskyi** [comment]
I think this needs a few paragraphs at the top setting readers expectations about what they will learn from the article. Maybe take the summary part and add more details there.

It seems that the article consists of two parts: **value** components and **operation** components. For value components you show how to use class inheritance to define components and ControlValueAccessor to create complex component types that can be used inside Angular Forms. I'd add some information on why it's needed, benefits, advantages over other existing approaches and so on. Not sure about what you were trying to show in the second part with operations components.

> for different value types
> For each value type, the following operations should be supported:
can you give examples of what is `value type` here? maybe provide more explantion, it's the first time I encounter such term

> We refer to these as operation components. Since all value types share some commonalities, **there is no need to develop value specific components for CRUD operations**.
are these separate components from value components? some code examples would help. Also, don't really understand the phrase I made bold.

**Comment by tobiasschweizer** [comment]
References:
- https://www.codementor.io/@godson.ukpere/creating-an-inline-edit-component-in-angular-2-nmkdlpxtq#the-easy-part
