### ISSUE TITLE
Viewer Value Component: TextValueAsHTMLComponent 

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/knora-ui-ng-lib#6]
Implement BaseValueComponent for `TextValue` for a `TextValueAsHtml`.

There is only read mode.

**Comment by tobiasschweizer** [comment]
@mdelez I did a similar thing for a custom GUI. You have to assign the HTML you got from Knora to a DOM element as in https://github.com/dhlab-basel/beol/blob/e0d9bd6edfd8864ad3714d51803ed5e87538682a/src/app/directives/mathjax.directive.ts#L204

In the component's constructor, you have to inject a reference to the DOM element as in https://github.com/dhlab-basel/beol/blob/e0d9bd6edfd8864ad3714d51803ed5e87538682a/src/app/directives/mathjax.directive.ts#L86

But maybe there are better ways to do this. In general, assigning HTML obtained from an external service is an Angular anti-pattern. I think we should try to generate the HTML in Angular from JSON that we get from Knora (that's a task for the future).

**Comment by mdelez** [comment]
@tobiasschweizer is there a way I can get a resource that returns a TextValueAsHTML? The current resource we've been using does not return one, only TextValueAsString and TextValueAsXML.

**Comment by tobiasschweizer** [comment]
No, I don't think so. I think you have to make something up.

**Comment by tobiasschweizer** [comment]
Or you can ask @benjamingeer if this could be added to "testding". Then it could be made available as static test data (mock resource).

**Comment by tobiasschweizer** [comment]
This requires a check for the actual type of class instance: `ReadTextValueAsString`, `ReadTextValueAsHtml`, or `ReadTextValueAsXml`.

In `projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts`:

```
ngOnInit() {

// if this.displayValue.type is "TextValue".
// figure out which class it is: ReadTextValueAsString`, `ReadTextValueAsHtml`, or `ReadTextValueAsXml`
// for the other types, it still works as is

// make a new member `valueType`, assign a string to it and check this string in ngSwitch in the the template

}
```

**Comment by tobiasschweizer** [comment]
```
<span [ngSwitch]="valueType">
    <kui-text-value-as-string #displayVal *ngSwitchCase="'TextValueAsString'" [mode]="mode"
      [displayValue]="displayValue"></kui-text-value-as-string>
    <kui-int-value #displayVal *ngSwitchCase="constants.IntValue" [mode]="mode" [displayValue]="displayValue">
    </kui-int-value>
```
